language: ruby

rvm:
  - 2.0.0-p647
  - 2.1.7
  - 2.2.3
  - ruby-head
  - jruby-19mode
  - jruby-head

sudo: false

script: bundle exec rspec

before_install:
  - gem install bundler -v 1.10.6

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

gemfile:
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
