language: ruby

rvm:
  - 2.5.5
  - 2.6.3
  - ruby-head
  - jruby-head

sudo: false

script:
  - bin/rspec
  - bin/rubocop

before_install:
  - gem install bundler -v 2.0.1

matrix:
  allow_failures:
    - rvm: ruby-head

gemfile:
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
