language: ruby

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
  - jruby-9.1.9.0

sudo: false

script: bundle exec rspec

before_install:
  - gem install bundler -v 1.15.0

matrix:
  allow_failures:
    - rvm: ruby-head

gemfile:
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
